### ISSUE TITLE
action status to lower case

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#28]
controlaction.py line 49 --> lowcase force on action status. Why? it should be one of (low case sensitive):
ActiveActionStatus
CompletedActionStatus
FailedActionStatus
PotentialActionStatus

**Comment by alastair** [comment]
Good catch.
This is because originally all of these values were lower-case, and we changed them because we realised that they were incorrect: https://github.com/trompamusic/ce-api/commit/d085989e12e9dcca40db2af7801f4ecb3d0f8d15

@pc2752 can you update this, and also add a check to verify that the field is one of the expected values (like we do for language)

**Comment by alastair** [comment]
This was fixed in https://github.com/trompamusic/trompa-ce-client/pull/29
