### ISSUE TITLE
mutation_add_controlaction_property

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#42]
It seems that mutation_add_controlaction_property() must be updated according to the new schema.

trompace.exceptions.QueryException: Query error 
1. Cannot query field "AddActionInterfaceThingInterface" on type "Mutation". Did you mean "AddActionInterfaceInstrument", "AddActionInterfaceLocation", "AddActionInterfaceResult", "AddThingInterfaceMainEntityOfPage", or "MergeActionInterfaceInstrument"?
 occurred

The template seems outdated

https://github.com/trompamusic/trompa-ce-client/blob/2fcad51a59d0337f2d824ee24a64acf42c0666fb/trompace/mutations/property.py#L35

qry:
mutation {
  AddActionInterfaceThingInterface(
    from: {identifier: "dc6006d8-e8d6-4287-96ee-22bac161220d", type: ControlAction}
    to: {identifier: "9a459253-a0e4-46b5-a500-5a94e9649a2f", type: Property}
    field: object
    ){
        from {
            __typename
      }
      to {
           __typename
           ... on Property{
            identifier
        }
      }
    }
}

**Comment by alastair** [comment]
Yes, this is the one that I commented to you during our talk.

On the CE at https://trompa-mtg.upf.edu/ce/, change the URL next to the "history" button to include the full url (https://trompa-mtg.upf.edu/ce/, by default it won't have the /ce/ part at the end)
Then refresh and click "Docs" on the right

From here you can search for the mutation that you need. My Guess is that it should be something like `MergeControlActionObject` (this is the type of the `from` plus the value of `field`). 
Note that we no longer need the 'field' value in this mutation because the mutation name contains it.

`Merge` means that it will add if it doesn't exist, but will skip it if it does exist. We use this in some other places in this library: https://github.com/trompamusic/trompa-ce-client/blob/2fcad51a59d0337f2d824ee24a64acf42c0666fb/trompace/mutations/musiccomposition.py#L194-L202

**Comment by aggelosgkiokas** [comment]
Indeed. I updated it (aggelosdev branch).
