### ISSUE TITLE
trompace.connection.submit_query authentication

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/trompa-ce-client#52]
It is not clear if the auth_required flag is related when we are over secure https or when we submit mutations (irrespectively we are over https)

https://github.com/trompamusic/trompa-ce-client/blob/12456bcbb81c4071cce96c8dcbd5efda04055203/trompace/connection.py#L33

**Comment by alastair** [comment]
From the documentation, this is required for CE Authentication, which is needed for mutations (`auth_required: If true, send an authentication key with this request`). This is required regardless of http or https. If you think that the documentation needs to be improved here, please make a suggestion and we can discuss it.

If it is easier, you can just send auth_required for _all_ requests. There is no problem if you send the authentication information for a query as well. I added this functionality for users who _only_ want to perform queries, so that they don't have to ask VD for an authentication key.
